theme: jekyll-theme-slate
title: Welcome to the Vicchain's homepage!
description: Vicchain developed its own hard- and software stacks enable companies to master the challenges of our digital society such as machine identity, product provenance and supply chain management.